name: Deploy

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
  push:
    branches:
      - master
      - client

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install

      - name: Run lint
        run: pnpm lint

      - name: Set environment variables for Vercel
        id: set-env
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/master" ]]; then
            echo "PRODUCTION=true" >> $GITHUB_ENV
          else
            echo "PRODUCTION=false" >> $GITHUB_ENV
          fi

      - uses: nexterias/actions-vercel@v1
        id: vercel
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          org-id: ${{ secrets.VERCEL_ORG_ID }}
          project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          production: ${{ env.PRODUCTION }}
          prebuilt: true
