name: Deployment

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

env:
  VERCEL_PREVIEW_HOOK: ${{ secrets.VERCEL_PREVIEW_HOOK }}
  VERCEL_PRODUCTION_HOOK: ${{ secrets.VERCEL_PRODUCTION_HOOK }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: preview
        if: github.event.workflow_run.conclusion == 'success' && github.ref != 'refs/heads/master'
        run: |
          curl -X POST "${{ env.VERCEL_PREVIEW_HOOK }}"

      - name: production
        if: github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/master'
        run: |
          curl -X POST "${{ env.VERCEL_PRODUCTION_HOOK }}"
